name: weihnachtsspecial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/illustrations/ bauble.png 
  - assets/illustrations/branch_BG.png
  - assets/illustrations/candy_BG.png
  - assets/illustrations/cup_cake.png
  - assets/illustrations/gift.png
  - assets/illustrations/gingerbread_man.png
  - assets/illustrations/glove.png
  - assets/illustrations/house.png
  - assets/illustrations/kai.png
  - assets/illustrations/mince_pig.png
  - assets/illustrations/party.png
  - assets/illustrations/santa.png
  - assets/illustrations/sleigh.png
  - assets/illustrations/snowball.png
  - assets/illustrations/stars.png
  - assets/illustrations/yule_cake.png

 - family: SF
    fonts:
      - asset: assets/fonts/SF-Pro-Display-Black.ttf
      - asset: assets/fonts/SF-Pro-Display-BlackItalic.ttf